import categories from './components/data/categories.js';
import { topContainerWrapper } from './components/view/topContainer.js';
import { headerWrapper } from './components/view/header.js';
import { newPostsWrapper } from './components/view/newPosts.js';
import { likedPostsWrapper } from './components/view/mostLikedPosts.js';
const myMobile = document.querySelector('.mobile');
myMobile.appendChild(headerWrapper);
myMobile.appendChild(topContainerWrapper);
myMobile.appendChild(newPostsWrapper);
myMobile.appendChild(likedPostsWrapper);
